name: publish-docker-image

on:
  push:
    branches:
      - Kan-10-Pipeline

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jira-project/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vite-jira:${{ github.sha }}
